---
title: "Split-Apply-Combine"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(lubridate)
library(ggplot2)
library(modelr)
library(purrr)
library(broom)
library(dplyr)
library(tidyr)
```

## Explore and model bike counts on 3 PDX bridges

```{r load data}
# getwd()
source("code/load_counts_for_rmd-sac.R")

```

```{r join weather and bridge data}
bikecounts_wx <- bikecounts %>% 
  left_join(wx, by = c("date" = "DATE")) %>% 
  select(date, bridge, total, TMIN, TMAX, PRCP)

```

dplyr joins are used. Left join used above turns each row in bikecounts (left) with each matching weather row (right) binding the weather columns by date.

```{r explore data graphically}
bikecounts_wx %>%  ggplot(aes(date, total,
       group = bridge, color = bridge)) +
  geom_line() + facet_grid(bridge ~.) +
  theme_bw()
#can also use facet_wrap above for a different look

bikecounts_wx %>%  ggplot(aes(date, total,
       group = bridge, color = bridge)) +
  geom_line() + facet_grid(bridge ~.) +
  theme_bw() + ylim(0, 10000)

```

```{r explore data summary stats}
# average daily count by bridge
bikecounts_wx %>% 
  group_by(bridge) %>% 
  summarize(avg_d_counts = mean(total))

# average monthly by bridge year
bikecounts_wx %>% 
  group_by(bridge, month(date), year(date)) %>% 
  summarize(avg_m_counts = mean(total)) %>% 
  View()

# daily average by month all time by bridge
avg_m <- bikecounts_wx %>% 
  group_by(bridge, month = month(date, label = T)) %>% 
  summarize(avg_daily_counts = mean(total)) %>% 
  as.data.frame()

ggplot(avg_m, aes(month, avg_daily_counts,
                  color = bridge)) +
  geom_point(size = 2) +
  theme_bw()

```

## Fitting Models in R

```{r model fitting}
# models return list objects describing fit
# fit of total daily counts
fit <- lm(total ~ TMIN + TMAX + PRCP + bridge,
          data = bikecounts_wx)
str(fit)
summary(fit)
plot(fit)

fit2 <- lm(log(total) ~ TMIN + TMAX + PRCP + bridge,
           data = bikecounts_wx)
summary(fit2)
plot(fit2)

# can pipe straight to summary if just trying to explore
lm(total ~ TMIN + TMAX + PRCP + bridge,
          data = bikecounts_wx) %>% summary()

# variable
fit_poly <- lm(total ~ TMIN + TMAX + I(TMAX^2) + PRCP + bridge,
          data = bikecounts_wx)
summary(fit_poly)
# str(coef(fit_poly)) # could access coefs here by name or position
coef(fit_poly)
f <- function(x) {198 * x + -0.99 * x^2} # from regression result

p <- ggplot(data = data.frame(x = 0),
            mapping = aes(x = x))

p + stat_function(fun = f, color = "darkgreen", size = 1) +
  xlim(0, 110) + xlab("deg F") + ylab("count")

```

```{r modelr intro}
bikecounts_wx <- bikecounts_wx %>% 
  add_predictions(fit_poly) %>%
  add_residuals(fit_poly) %>% 
  mutate(pred = pred, resid = resid)
head(bikecounts_wx)

ggplot() +
  geom_line(data = bikecounts_wx, aes(date, total),
             color = "darkgrey") +
  geom_line(data = bikecounts_wx, aes(date, pred),
            color = "blue") +
  facet_grid(bridge ~ ., scales = "free") +
  ylim(c(0,10000)) + theme_bw()

```

```{r split-apply-combine}
bw_nested <- bikecounts_wx %>% 
  group_by(bridge) %>% 
  nest()
View(bw_nested)

# fit to single bridge
lm(total ~ TMIN + TMAX + PRCP,
          data = bw_nested[[1, "data"]]) %>% # for just Hawthorne
  summary()

# fit to 3 bridges
fit_func <- function(df){
  lm(total ~ TMIN + TMAX + PRCP,
     data = df)
}

fit_func2 <- function(df){
  lm(log(total) ~ TMIN + TMAX + PRCP,
     data = df)
}


# one at a time via function
fit_func(bw_nested[[1, "data"]])

# two at a time through tidyverse. mapped to lm function
fits <- purrr::map(bw_nested$data[1:2],
                   fit_func)
fits
str(fits)

# three at a time using fit_func
bw_nested <- bw_nested %>% 
  mutate(fit = purrr::map(data, fit_func2),
         tidy = purrr::map(fit, tidy),
         glance = purrr::map(fit, glance))

# unpack/unnest or combine results. One bridge for example
broom::tidy(bw_nested$fit[[1]])

# unpack for all 3
bw_nested %>% 
  unnest(glance) %>% 
  arrange(desc(r.squared))

bw_nested %>% 
  select(bridge, tidy) %>% 
  unnest(tidy) %>% 
  arrange(term, estimate, bridge) %>% 
  View()

```

